# Generated by Django 5.1.2 on 2025-01-11 06:44

import django.contrib.postgres.fields
import homeFix.accounts.models.app_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='job_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('renovation', 'Renovation'), ('maintenance', 'Maintenance'), ('landscaping', 'Landscaping'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=30), blank=True, default=homeFix.accounts.models.app_profile.JobCategory, size=None),
        ),
    ]
